kind: Service
apiVersion: v1
metadata:
  name: tjmk-hospital-webapi
spec:
  selector:
    pod: tjmk-hospital-webapi-label
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: webapi-port