/*
 * Waiting List Api
 *
 * Hospital Waiting List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xkacani@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package hospital_wl

import (
	"github.com/gin-gonic/gin"
)

type HospitalWaitingListAPI interface {


    // CreateWaitingListEntry Post /api/waiting-list/:hospitalId/entries
    // Saves new entry into waiting list 
     CreateWaitingListEntry(c *gin.Context)

    // DeleteWaitingListEntry Delete /api/waiting-list/:hospitalId/entries/:entryId
    // Deletes specific entry 
     DeleteWaitingListEntry(c *gin.Context)

    // GetWaitingListEntries Get /api/waiting-list/:hospitalId/entries
    // Provides the hospital waiting list 
     GetWaitingListEntries(c *gin.Context)

    // GetWaitingListEntry Get /api/waiting-list/:hospitalId/entries/:entryId
    // Provides details about waiting list entry 
     GetWaitingListEntry(c *gin.Context)

    // UpdateWaitingListEntry Put /api/waiting-list/:hospitalId/entries/:entryId
    // Updates specific entry 
     UpdateWaitingListEntry(c *gin.Context)

}