/*
 * Waiting List Api
 *
 * Hospital Waiting List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xkacani@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package hospital_wl

import (
	"github.com/gin-gonic/gin"
)

type HospitalConditionsAPI interface {


    // GetConditions Get /api/waiting-list/:hospitalId/condition
    // Provides the list of conditions associated with hospital 
     GetConditions(c *gin.Context)

}